### ISSUE TITLE
Enhancement to allow message to use scope

### ISSUE THREAD

**Issue by ahazelwood** [eriktufvesson/ngBootbox#10]
Rather than having a static ng-bootbox-confirm message, it would be nice if one could either:  a) Integrate in a current scope variable directly, or b) call a scope function to get the message. 

For example, imagine a button:  
&lt;button ng-bootbox-confirm="Delete the user?"&gt;&lt;/button&gt;

Instead it would be nice to integrate in something like:  
&lt;button ng-bootbox-confirm="Delete {customer.name}?"&gt;&lt;/button&gt;
   -or-  
&lt;button ng-bootbox-confirm="deleteMessage(customer)"&gt;&lt;/button&gt;
... 
$scope.deleteMessage = function(customer) {
   return 'Delete ' + customer.name + '?';
};

**Comment by eriktufvesson** [comment]
Hi,

For your first example I would suggest something like this:

Some kind of customer list:

    <ul ng-repeat="customer in customers">
        <li>
            {{customer.name}}
            <button ng-bootbox-confirm="Delete {{customer.name}}?" ng-bootbox-confirm-action="deleteCustomer(customer)">Delete</button>
        </li>
    </ul>

For the second example I would suggest using the $ngBootbox service.

    <button ng-click="deleteCustomer(customer)">Delete</button>

...

    $scope.deleteCustomer = function(customer) {
        $ngBootbox.confirm('Delete ' + customer.name +'?')
            .then(function() {
                //Delete user here
            }, function() {
                //Not confirmed. Do nothing.
            });
    };

**Comment by ahazelwood** [comment]
The first option worked, I guess I had some issues with other parts earlier when I first attempted that.  The second option I couldn't get to work with $ngBootbox because angular complains of an unknown provider.  I've tried including the ngBootbox module in the list of dependencies for my controller, but no work.  Do you have an actual working example that you could provide (including the controller definition and then usage)?

Thanks.

**Comment by eriktufvesson** [comment]
Hi again,

I think you are missing to inject $ngBootbox (the service) into your controller. I have constructed a working example here: http://embed.plnkr.co/gtNP6J/preview
