### ISSUE TITLE
Destroying bootbox

### ISSUE THREAD

**Issue by supys12** [eriktufvesson/ngBootbox#12]
Is there any way to destroy bootbox.
beacuse hideAll() function just hides the bootbox it doesnt destroy it.

**Comment by vlapo** [comment]
I think this is issue for [bootbox.js](https://github.com/makeusabrew/bootbox). ngBootbox is only AngularJS wrapper and use bootbox.js API. So this issue should be closed.

**Comment by eriktufvesson** [comment]
Ok, closing the issue
