### ISSUE TITLE
ReferenceError: $http is not defined

### ISSUE THREAD

**Issue by vlapo** [eriktufvesson/ngBootbox#15]
Hi, I have problem with custom dialog over ngBootbox service. Have anybody this problem? 

```
ReferenceError: $http is not defined
    at getTemplate (ngBootbox.js:180)
    at Object.customDialog (ngBootbox.js:154)
    ...
```

**Comment by eriktufvesson** [comment]
Hi vlapo! Could you maybe put together an example where this doesn't work? For instance a [plunk](http://plnkr.co/). Then I can take a closer look.

Regards,
Erik

**Comment by oletok** [comment]
Hi there,

Mr. Erik Thank you for your good module.
I met the same problem. At #117 in dist/ngBootbox.js  "$http" is not injected. I added it and looks OK.

oletok

**Comment by vlapo** [comment]
oletok is right. In version 0.0.4 is missing injection of $http. 

In v0.0.5 is all right.
