### ISSUE TITLE
(ngBootbox + bootbox) + RequireJS + AngularJS = "ReferenceError: bootbox is not defined"

### ISSUE THREAD

**Issue by budhajeewa** [eriktufvesson/ngBootbox#18]
ngBootbox seems a really useful package when using bootbox with AngularJS. Therefore I really wish I'd be able to use this.

I use RequireJS to load packages for my application. I have configured my `requirejs.conf.js` like below:

```
require.config({
	paths: {
		'angular': '../vendor/angular/angular.min',
		'jquery': '../vendor/jquery/dist/jquery.min',
		'twbs': '../vendor/bootstrap/dist/js/bootstrap.min',
		'bootbox': '../vendor/bootbox/bootbox',
		'ngBootbox': '../vendor/ngBootbox/dist/ngBootbox'
	},
	shim: {
		'app' : {
			'angular',
			'jquery',
			'twbs',
			'bootbox',
			'ngBootbox'
		},
		'angular': {
			deps: [
				'jquery',
			]
		},
		'twbs': {
			deps: [
				'jquery'
				]
		},
		'ngBootbox': {
			deps: [
				'jquery',
				'angular',
				'twbs',
				'bootbox'
				]
		},
		'bootbox': {
			deps: [
				'angular'
			],
			exports: 'bootbox'
		}
	}
});
```

When I monitor network activities, I can see all the required JS files in your documentation (jQuery, AngularJS, Bootstrap, Bootbox, ngBootbox) loading.

I have a button like following in the view:

```
<button
	class="btn btn-danger btn-xs"
	ng-bootbox-confirm="Are you sure you want to confirm this?"
	ng-bootbox-confirm-action="console.log(1])"
	ng-bootbox-confirm-action-cancel="console.log(2)"
>
	Delete
</button>
```

When I click it, I get the following error.

```
ReferenceError: bootbox is not defined
```

Have you checked your package with RequireJS? Am I doing something wrong?

What it looks like, is that bootbox is not being exposed to your package, even though it is specified as one of dependencies of your package.

I'd highly appreciate a fix for this.

**Comment by eriktufvesson** [comment]
Support for require.js and an example (examples/example-2) is added. Thanks for the point out!

**Comment by jesujcastillom** [comment]
Is it possible to make it work with JSPM/SystemJS? I'm getting this same issue using SystemJS
