### ISSUE TITLE
bootbox is undefined in $window

### ISSUE THREAD

**Issue by hanssl** [eriktufvesson/ngBootbox#26]
I am trying to use ngBootbox with a meanjs project.  I have added ngBootbox as a dependency to my app.  When I try to call any of the bootbox functions I get an error that bootbox is undefined.  I set a breakpoint on the alert function and confirmed that $window.bootbox is undefined.

Did I miss a step in adding ngBootbox to my project or is this a bug?

![screen shot 2015-10-13 at 10 52 00 am](https://cloud.githubusercontent.com/assets/649957/10462036/96555f54-7199-11e5-94c3-8f952e6cde1b.png)

**Comment by eriktufvesson** [comment]
Seems to me that you havn't added [bootbox.js](http://bootboxjs.com/) to your project.

**Comment by hanssl** [comment]
My bower.json file includes the following dependencies:
"ngBootbox": "~0.1.1",
"bootbox": ">=4.4.0"

My package.json file includes the following dependencies:
"bootbox": "^4.4.0"

Is there another step that I need to perform to add bootbox.js to my project?

**Comment by eriktufvesson** [comment]
When I look at your screenshot, it looks like you have forgotten to include bootbox.js in your index.html. Also make sure you have jQuery included in index.html.

**Comment by hanssl** [comment]
Your comment helped me track down the issue.  Meanjs includes js files that are enumerated in 'config/assets/default.js'.  After I added the bootbox, jquery, and bootstrap references then I could call ngBootbox functions.  Thank you.
