### ISSUE TITLE
Publish into NPM

### ISSUE THREAD

**Issue by lucastschmidt** [eriktufvesson/ngBootbox#27]
Hey man, thanks for this, but your module is only available on Bower I think.

It would be cool to be available on npm as well, since lots of users are using browserify and there is no need for Bower usage in this case. Thanks.

**Comment by eriktufvesson** [comment]
Hi!

Good point! I have published it to npm now. Install using:
     
     npm install --save ngbootbox

Notice the lowercase *b*

**Comment by lucastschmidt** [comment]
@eriktufvesson thanks, I will try later on.
