### ISSUE TITLE
Values does not update the HTML

### ISSUE THREAD

**Issue by PiyushRamuka** [eriktufvesson/ngBootbox#28]
Hi,

The bootbox works but my view is not updated automatically. I have to use $scope.$apply within the callback to update the frontend. Here is the code. Am I missing something?

<code>
$ngBootbox.customDialog({
                    message: "Will remove all existing items",
                    title: "Are you sure?",
                    buttons: {
                        warning: {
                            label: "No",
                            className: "btn-warning",
                            callback: function() {
                                console.log("No clicked");
                            }`
                        },
                        success: {
                            label: "Yes",
                            className: "btn-success",
                            callback: function() {
                                console.log("Yes clicked");
                                _this.supplyItems = [];
                            }
                        }
                   }
              });
</code>

**Comment by eriktufvesson** [comment]
Hi,

The custom dialog callbacks are handled by the bootbox.js code, and since this is non-angular code, you need to wrap any scope updates in $scope.$apply(),

Best regards,
Erik
