### ISSUE TITLE
change locale globally, with angular.config

### ISSUE THREAD

**Issue by CaledoniaProject** [eriktufvesson/ngBootbox#29]
Hi,

I'm trying to do something like this,

```
app.config(['ngBootbox', function(ngBootbox) {
   ngBootbox.setLocale ('xxx');
}]);
```

But angular does not run with it, any ideas? Already added ngBootbox as dependencies, and it works great.

Now I just need to avoid setting the locale in every controllers ...

**Comment by eriktufvesson** [comment]
Hi,

A provider is now added in v0.1.3 of ngBootbox.

You can use it like this:

    angular.module('yourApp')
        .config(function($ngBootboxConfigProvider) {
            $ngBootboxConfigProvider.setDefaultLocale('sv');
            
            $ngBootboxConfigProvider.addLocale('ex', { OK: 'OK', CANCEL: 'Avbryt', CONFIRM: 'Bekräfta' });
            
            $ngBootboxConfigProvider.removeLocale('ex');
         })
         .controller('TestCtrl', function($ngBootboxConfig) {
            var defaultLocale = $ngBootboxConfig.getDefaultLocale();  
         });

**Comment by CaledoniaProject** [comment]
great job! Just applied to my project
