### ISSUE TITLE
How to set custom dialog's size?

### ISSUE THREAD

**Issue by shangdiyisi** [eriktufvesson/ngBootbox#32]
How to set custom dialog's size?

    ng-bootbox-size="large"

This is not working.

**Comment by vlapo** [comment]
You have to use ng-bootbox-options. E.g.

Controller:
```javascript
$scope.dialogOptions = {
     size: 'large',
};
```

View:
```html
<button
    <!-- ..... -->
    ng-bootbox-options="dialogOptions"
    <!-- ..... -->
>Dialog open</button>
```

**Comment by shangdiyisi** [comment]
@vlapo  How to set message for custom dialog?

**Comment by vlapo** [comment]
Did you read documentation (main page of github). There is https://github.com/eriktufvesson/ngBootbox#ng-bootbox-custom-dialog

**Comment by shangdiyisi** [comment]
@vlapo  I used ng-repeat directive, every row's ng-bootbox-options is different, how to set a parameter to ng-bootbox-options?

**Comment by shangdiyisi** [comment]
Thank you very much!

**Comment by dnyaneshwaruttarwar** [comment]
size: 'large' is not working for me !!
