### ISSUE TITLE
support for className?

### ISSUE THREAD

**Issue by tarlepp** [eriktufvesson/ngBootbox#5]
I didn't find anything to get this option value to working? Basically usage is like

```
bootbox.dialog({
    message: "test",
    className: "foobar"
})
```

And that will add `foobar` class to main modal div. This is very usefull when you need to override some basic styling of modal itself.

**Comment by eriktufvesson** [comment]
Hi again,

Sorry for the late reply. Thanks for pointing out that I should reference
the issues in my commits. I'm kind of new to Github and this is my first
open source project.

I have now added a ng-bootbox-options parameter to the custom dialog. You
can use it like this:
https://gist.github.com/eriktufvesson/d388ea4a44da2ec5548f

I have also added a setDefaults method to the $ngBootbox factory.

To my knowledge, you can't specify specific options for the alerts,
confirms and prompts in bootbox. However, the setDefaults apply to those.
Please correct me if I'm wrong, but I can't find anything on this matter in
the API Docs.

Best regards
Erik

2014-12-10 20:15 GMT+01:00 Tarmo Leppänen <notifications@github.com>:
