### ISSUE TITLE
Support for different prompts?

### ISSUE THREAD

**Issue by tarlepp** [eriktufvesson/ngBootbox#7]
There is multiple prompt types in bootbox, it would be nice to support all of those.

**Comment by eriktufvesson** [comment]
Hi,

I'm not sure what you mean by this. Could you provide a code example?

/Erik

**Comment by eriktufvesson** [comment]
The commit I just did had the wrong issue number. It was for #8. Sorry for this...

**Comment by dalibormesaric** [comment]
Something like this? https://github.com/makeusabrew/bootbox/issues/143
