### ISSUE TITLE
Custom dialog as service

### ISSUE THREAD

**Issue by giolvani** [eriktufvesson/ngBootbox#8]
By $ngBootbox service, just alert, confirm and prompt are available, it would be very nice if the custom dialog was available as well...

**Comment by eriktufvesson** [comment]
Hi,

Support for this is now added. You can use it by doing something like this: 

    $scope.openCustomDialogWithService = function() {
        $ngBootbox.customDialog($scope.customDialogOptions);
      };

      $scope.customDialogOptions = {
          message: 'This is a message!',
          title: 'The best title!',
          onEscape: function() {
              $log.info('Escape was pressed');
          },
          show: true,
          backdrop: false,
          closeButton: true,
          animate: true,
          className: 'test-class',
          buttons: $scope.customDialogButtons
      };

      $scope.customDialogButtons = {
          warning: {
              label: "Warning!",
              className: "btn-warning",
              callback: function() { $scope.addAction('Warning', false); }
          },
          success: {
              label: "Success!",
              className: "btn-success",
              callback: function() { $scope.addAction('Success!', true); }
          },
          danger: {
              label: "Danger!",
              className: "btn-danger",
              callback: function() { $scope.addAction('Danger!', false); }
          },
          main: {
              label: "Click ME!",
              className: "btn-primary",
              callback: function() { $scope.addAction('Main...!', true); }
          }
      };
